drop table if exists students_classes_teachers;
create table students_classes_teachers (
	ID INT,
	student_id VARCHAR(50),
	student_first VARCHAR(50),
	student_last VARCHAR(50),
	student_gender VARCHAR(50),
	class VARCHAR(23),
	teacher VARCHAR(18)
);
insert into students_classes_teachers (ID, student_id, student_first, student_last, student_gender, class, teacher) 
values
(1, 1, 'Emelen', 'Crossingham', 'Male', 'Algebra 1', 'Jocko Arkley'),
(2, 1, 'Emelen', 'Crossingham', 'Male', 'Biology', 'Tonya Keeping'),
(3, 1, 'Emelen', 'Crossingham', 'Male', 'Geography', 'Frayda Dudson'),
(4, 1, 'Emelen', 'Crossingham', 'Male', 'Contemporary literature', 'Iggy Gentle'),
(5, 1, 'Emelen', 'Crossingham', 'Male', 'Debate', 'Ainslee Hawkes'),
(6, 1, 'Emelen', 'Crossingham', 'Male', 'Health', 'Dorey Burn'),
(7, 1, 'Emelen', 'Crossingham', 'Male', 'Swimming', 'Zedekiah Dell Casa'),
(8, 1, 'Emelen', 'Crossingham', 'Male', 'Auto mechanics', 'Ransom Mingauld'),
(9, 2, 'Blanca', 'Greedier', 'Female', 'Algebra 2', 'Robin Baumber'),
(10, 2, 'Blanca', 'Greedier', 'Female', 'Chemistry', 'Barbey Dudlestone'),
(11, 2, 'Blanca', 'Greedier', 'Female', 'Psychology', 'Jocko Arkley'),
(12, 2, 'Blanca', 'Greedier', 'Female', 'Creative writing', 'Tonya Keeping'),
(13, 2, 'Blanca', 'Greedier', 'Female', 'Journalism', 'Frayda Dudson'),
(14, 2, 'Blanca', 'Greedier', 'Female', 'Jazz band', 'Iggy Gentle'),
(15, 2, 'Blanca', 'Greedier', 'Female', 'Weight training', 'Ainslee Hawkes'),
(16, 2, 'Blanca', 'Greedier', 'Female', 'Driver education', 'Dorey Burn'),
(17, 3, 'Conrad', 'Haggerty', 'Male', 'Calculus', 'Zedekiah Dell Casa'),
(18, 3, 'Conrad', 'Haggerty', 'Male', 'Environmental science', 'Ransom Mingauld'),
(19, 3, 'Conrad', 'Haggerty', 'Male', 'US government', 'Robin Baumber'),
(20, 3, 'Conrad', 'Haggerty', 'Male', 'American literature', 'Barbey Dudlestone'),
(21, 3, 'Conrad', 'Haggerty', 'Male', 'Choir', 'Jocko Arkley'),
(22, 3, 'Conrad', 'Haggerty', 'Male', 'Music theory', 'Tonya Keeping'),
(23, 3, 'Conrad', 'Haggerty', 'Male', 'Film', 'Frayda Dudson'),
(24, 3, 'Conrad', 'Haggerty', 'Male', 'JROTC', 'Iggy Gentle'),
(25, 4, 'Gaby', 'Dodworth', 'Female', 'Geometry', 'Ainslee Hawkes'),
(26, 4, 'Gaby', 'Dodworth', 'Female', 'Physics', 'Dorey Burn'),
(27, 4, 'Gaby', 'Dodworth', 'Female', 'US history', 'Zedekiah Dell Casa'),
(28, 4, 'Gaby', 'Dodworth', 'Female', 'British literature', 'Ransom Mingauld'),
(29, 4, 'Gaby', 'Dodworth', 'Female', 'Dance', 'Robin Baumber'),
(30, 4, 'Gaby', 'Dodworth', 'Female', 'Orchestra', 'Barbey Dudlestone'),
(31, 4, 'Gaby', 'Dodworth', 'Female', 'Sculpture', 'Jocko Arkley'),
(32, 4, 'Gaby', 'Dodworth', 'Female', 'Woodworking', 'Tonya Keeping'),
(33, 5, 'Tyne', 'Bamborough', 'Female', 'Statistics', 'Frayda Dudson'),
(34, 5, 'Tyne', 'Bamborough', 'Female', 'Trigonometry', 'Iggy Gentle'),
(35, 5, 'Tyne', 'Bamborough', 'Female', 'World history', 'Ainslee Hawkes'),
(36, 5, 'Tyne', 'Bamborough', 'Female', 'Modern literature', 'Dorey Burn'),
(37, 5, 'Tyne', 'Bamborough', 'Female', 'Drama', 'Zedekiah Dell Casa'),
(38, 5, 'Tyne', 'Bamborough', 'Female', 'Percussion', 'Ransom Mingauld'),
(39, 5, 'Tyne', 'Bamborough', 'Female', 'Photography', 'Robin Baumber'),
(40, 5, 'Tyne', 'Bamborough', 'Female', 'Computer Science', 'Barbey Dudlestone'),
(41, 6, 'Carley', 'Shatliffe', 'Female', 'Algebra 1', 'Jocko Arkley'),
(42, 6, 'Carley', 'Shatliffe', 'Female', 'Biology', 'Tonya Keeping'),
(43, 6, 'Carley', 'Shatliffe', 'Female', 'Geography', 'Frayda Dudson'),
(44, 6, 'Carley', 'Shatliffe', 'Female', 'Contemporary literature', 'Iggy Gentle'),
(45, 6, 'Carley', 'Shatliffe', 'Female', 'Debate', 'Ainslee Hawkes'),
(46, 6, 'Carley', 'Shatliffe', 'Female', 'Health', 'Dorey Burn'),
(47, 6, 'Carley', 'Shatliffe', 'Female', 'Swimming', 'Zedekiah Dell Casa'),
(48, 6, 'Carley', 'Shatliffe', 'Female', 'Auto mechanics', 'Ransom Mingauld'),
(49, 7, 'Giorgia', 'Tures', 'Female', 'Algebra 2', 'Robin Baumber'),
(50, 7, 'Giorgia', 'Tures', 'Female', 'Chemistry', 'Barbey Dudlestone'),
(51, 7, 'Giorgia', 'Tures', 'Female', 'Psychology', 'Jocko Arkley'),
(52, 7, 'Giorgia', 'Tures', 'Female', 'Creative writing', 'Tonya Keeping'),
(53, 7, 'Giorgia', 'Tures', 'Female', 'Journalism', 'Frayda Dudson'),
(54, 7, 'Giorgia', 'Tures', 'Female', 'Jazz band', 'Iggy Gentle'),
(55, 7, 'Giorgia', 'Tures', 'Female', 'Weight training', 'Ainslee Hawkes'),
(56, 7, 'Giorgia', 'Tures', 'Female', 'Driver education', 'Dorey Burn'),
(57, 8, 'Ephrem', 'Harral', 'Male', 'Calculus', 'Zedekiah Dell Casa'),
(58, 8, 'Ephrem', 'Harral', 'Male', 'Environmental science', 'Ransom Mingauld'),
(59, 8, 'Ephrem', 'Harral', 'Male', 'US government', 'Robin Baumber'),
(60, 8, 'Ephrem', 'Harral', 'Male', 'American literature', 'Barbey Dudlestone'),
(61, 8, 'Ephrem', 'Harral', 'Male', 'Choir', 'Jocko Arkley'),
(62, 8, 'Ephrem', 'Harral', 'Male', 'Music theory', 'Tonya Keeping'),
(63, 8, 'Ephrem', 'Harral', 'Male', 'Film', 'Frayda Dudson'),
(64, 8, 'Ephrem', 'Harral', 'Male', 'JROTC', 'Iggy Gentle'),
(65, 9, 'Si', 'Broxup', 'Male', 'Geometry', 'Ainslee Hawkes'),
(66, 9, 'Si', 'Broxup', 'Male', 'Physics', 'Dorey Burn'),
(67, 9, 'Si', 'Broxup', 'Male', 'US history', 'Zedekiah Dell Casa'),
(68, 9, 'Si', 'Broxup', 'Male', 'British literature', 'Ransom Mingauld'),
(69, 9, 'Si', 'Broxup', 'Male', 'Dance', 'Robin Baumber'),
(70, 9, 'Si', 'Broxup', 'Male', 'Orchestra', 'Barbey Dudlestone'),
(71, 9, 'Si', 'Broxup', 'Male', 'Sculpture', 'Jocko Arkley'),
(72, 9, 'Si', 'Broxup', 'Male', 'Woodworking', 'Tonya Keeping'),
(73, 10, 'Gerado', 'Pimblotte', 'Male', 'Statistics', 'Frayda Dudson'),
(74, 10, 'Gerado', 'Pimblotte', 'Male', 'Trigonometry', 'Iggy Gentle'),
(75, 10, 'Gerado', 'Pimblotte', 'Male', 'World history', 'Ainslee Hawkes'),
(76, 10, 'Gerado', 'Pimblotte', 'Male', 'Modern literature', 'Dorey Burn'),
(77, 10, 'Gerado', 'Pimblotte', 'Male', 'Drama', 'Zedekiah Dell Casa'),
(78, 10, 'Gerado', 'Pimblotte', 'Male', 'Percussion', 'Ransom Mingauld'),
(79, 10, 'Gerado', 'Pimblotte', 'Male', 'Photography', 'Robin Baumber'),
(80, 10, 'Gerado', 'Pimblotte', 'Male', 'Computer Science', 'Barbey Dudlestone'),
(81, 11, 'Merry', 'Malley', 'Male', 'Algebra 1', 'Jocko Arkley'),
(82, 11, 'Merry', 'Malley', 'Male', 'Biology', 'Tonya Keeping'),
(83, 11, 'Merry', 'Malley', 'Male', 'Geography', 'Frayda Dudson'),
(84, 11, 'Merry', 'Malley', 'Male', 'Contemporary literature', 'Iggy Gentle'),
(85, 11, 'Merry', 'Malley', 'Male', 'Debate', 'Ainslee Hawkes'),
(86, 11, 'Merry', 'Malley', 'Male', 'Health', 'Dorey Burn'),
(87, 11, 'Merry', 'Malley', 'Male', 'Swimming', 'Zedekiah Dell Casa'),
(88, 11, 'Merry', 'Malley', 'Male', 'Auto mechanics', 'Ransom Mingauld'),
(89, 12, 'Ferrel', 'Brenneke', 'Female', 'Algebra 2', 'Robin Baumber'),
(90, 12, 'Ferrel', 'Brenneke', 'Male', 'Chemistry', 'Barbey Dudlestone'),
(91, 12, 'Ferrel', 'Brenneke', 'Female', 'Psychology', 'Jocko Arkley'),
(92, 12, 'Ferrel', 'Brenneke', 'Female', 'Creative writing', 'Tonya Keeping'),
(93, 12, 'Ferrel', 'Brenneke', 'Male', 'Journalism', 'Frayda Dudson'),
(94, 12, 'Ferrel', 'Brenneke', 'Female', 'Jazz band', 'Iggy Gentle'),
(95, 12, 'Ferrel', 'Brenneke', 'Female', 'Weight training', 'Ainslee Hawkes'),
(96, 12, 'Ferrel', 'Brenneke', 'Female', 'Driver education', 'Dorey Burn'),
(97, 13, 'Warren', 'Cabena', 'Male', 'Calculus', 'Zedekiah Dell Casa'),
(98, 13, 'Warren', 'Cabena', 'Male', 'Environmental science', 'Ransom Mingauld'),
(99, 13, 'Warren', 'Cabena', 'Male', 'US government', 'Robin Baumber'),
(100, 13, 'Warren', 'Cabena', 'Male', 'American literature', 'Barbey Dudlestone'),
(101, 13, 'Warren', 'Cabena', 'Male', 'Choir', 'Jocko Arkley'),
(102, 13, 'Warren', 'Cabena', 'Male', 'Music theory', 'Tonya Keeping'),
(103, 13, 'Warren', 'Cabena', 'Male', 'Film', 'Frayda Dudson'),
(104, 13, 'Warren', 'Cabena', 'Male', 'JROTC', 'Iggy Gentle'),
(105, 14, 'Alleen', 'Duffell', 'Female', 'Geometry', 'Ainslee Hawkes'),
(106, 14, 'Alleen', 'Duffell', 'Female', 'Physics', 'Dorey Burn'),
(107, 14, 'Alleen', 'Duffell', 'Female', 'US history', 'Zedekiah Dell Casa'),
(108, 14, 'Alleen', 'Duffell', 'Female', 'British literature', 'Ransom Mingauld'),
(109, 14, 'Alleen', 'Duffell', 'Female', 'Dance', 'Robin Baumber'),
(110, 14, 'Alleen', 'Duffell', 'Female', 'Orchestra', 'Barbey Dudlestone'),
(111, 14, 'Alleen', 'Duffell', 'Female', 'Sculpture', 'Jocko Arkley'),
(112, 14, 'Alleen', 'Duffell', 'Female', 'Woodworking', 'Tonya Keeping'),
(113, 15, 'Marilee', 'Verring', 'Female', 'Statistics', 'Frayda Dudson'),
(114, 15, 'Marilee', 'Verring', 'Female', 'Trigonometry', 'Iggy Gentle'),
(115, 15, 'Marilee', 'Verring', 'Female', 'World history', 'Ainslee Hawkes'),
(116, 15, 'Marilee', 'Verring', 'Female', 'Modern literature', 'Dorey Burn'),
(117, 15, 'Marilee', 'Verring', 'Female', 'Drama', 'Zedekiah Dell Casa'),
(118, 15, 'Marilee', 'Verring', 'Female', 'Percussion', 'Ransom Mingauld'),
(119, 15, 'Marilee', 'Verring', 'Female', 'Photography', 'Robin Baumber'),
(120, 15, 'Marilee', 'Verring', 'Female', 'Computer Science', 'Barbey Dudlestone'),
(121, 16, 'Meade', 'Milazzo', 'Male', 'Algebra 1', 'Jocko Arkley'),
(122, 16, 'Meade', 'Milazzo', 'Male', 'Biology', 'Tonya Keeping'),
(123, 16, 'Meade', 'Milazzo', 'Male', 'Geography', 'Frayda Dudson'),
(124, 16, 'Meade', 'Milazzo', 'Male', 'Contemporary literature', 'Iggy Gentle'),
(125, 16, 'Meade', 'Milazzo', 'Male', 'Debate', 'Ainslee Hawkes'),
(126, 16, 'Meade', 'Milazzo', 'Male', 'Health', 'Dorey Burn'),
(127, 16, 'Meade', 'Milazzo', 'Male', 'Swimming', 'Zedekiah Dell Casa'),
(128, 16, 'Meade', 'Milazzo', 'Male', 'Auto mechanics', 'Ransom Mingauld'),
(129, 17, 'Kleon', 'Spleving', 'Male', 'Algebra 2', 'Robin Baumber'),
(130, 17, 'Kleon', 'Spleving', 'Male', 'Chemistry', 'Barbey Dudlestone'),
(131, 17, 'Kleon', 'Spleving', 'Male', 'Psychology', 'Jocko Arkley'),
(132, 17, 'Kleon', 'Spleving', 'Male', 'Creative writing', 'Tonya Keeping'),
(133, 17, 'Kleon', 'Spleving', 'Male', 'Journalism', 'Frayda Dudson'),
(134, 17, 'Kleon', 'Spleving', 'Male', 'Jazz band', 'Iggy Gentle'),
(135, 17, 'Kleon', 'Spleving', 'Male', 'Weight training', 'Ainslee Hawkes'),
(136, 17, 'Kleon', 'Spleving', 'Male', 'Driver education', 'Dorey Burn'),
(137, 18, 'Pollyanna', 'Godball', 'Female', 'Calculus', 'Zedekiah Dell Casa'),
(138, 18, 'Pollyanna', 'Godball', 'Female', 'Environmental science', 'Ransom Mingauld'),
(139, 18, 'Pollyanna', 'Godball', 'Female', 'US government', 'Robin Baumber'),
(140, 18, 'Pollyanna', 'Godball', 'Female', 'American literature', 'Barbey Dudlestone'),
(141, 18, 'Pollyanna', 'Godball', 'Female', 'Choir', 'Jocko Arkley'),
(142, 18, 'Pollyanna', 'Godball', 'Female', 'Music theory', 'Tonya Keeping'),
(143, 18, 'Pollyanna', 'Godball', 'Female', 'Film', 'Frayda Dudson'),
(144, 18, 'Pollyanna', 'Godball', 'Female', 'JROTC', 'Iggy Gentle'),
(145, 19, 'Patrice', 'Boland', 'Male', 'Geometry', 'Ainslee Hawkes'),
(146, 19, 'Patrice', 'Boland', 'Male', 'Physics', 'Dorey Burn'),
(147, 19, 'Patrice', 'Boland', 'Male', 'US history', 'Zedekiah Dell Casa'),
(148, 19, 'Patrice', 'Boland', 'Male', 'British literature', 'Ransom Mingauld'),
(149, 19, 'Patrice', 'Boland', 'Male', 'Dance', 'Robin Baumber'),
(150, 19, 'Patrice', 'Boland', 'Male', 'Orchestra', 'Barbey Dudlestone'),
(151, 19, 'Patrice', 'Boland', 'Male', 'Sculpture', 'Jocko Arkley'),
(152, 19, 'Patrice', 'Boland', 'Male', 'Woodworking', 'Tonya Keeping'),
(153, 20, 'Gamaliel', 'Holtaway', 'Male', 'Statistics', 'Frayda Dudson'),
(154, 20, 'Gamaliel', 'Holtaway', 'Male', 'Trigonometry', 'Iggy Gentle'),
(155, 20, 'Gamaliel', 'Holtaway', 'Male', 'World history', 'Ainslee Hawkes'),
(156, 20, 'Gamaliel', 'Holtaway', 'Male', 'Modern literature', 'Dorey Burn'),
(157, 20, 'Gamaliel', 'Holtaway', 'Male', 'Drama', 'Zedekiah Dell Casa'),
(158, 20, 'Gamaliel', 'Holtaway', 'Male', 'Percussion', 'Ransom Mingauld'),
(159, 20, 'Gamaliel', 'Holtaway', 'Male', 'Photography', 'Robin Baumber'),
(160, 20, 'Gamaliel', 'Holtaway', 'Male', 'Computer Science', 'Barbey Dudlestone');